name: Notify Telegram

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send success notification to Telegram
        uses: peter-evans/telegram-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: "Ты справился, деплой прошел!"
